title = "Fallon Events"
featured_image = '/static/images/cover.jpg'

[module]
  [module.hugoVersion]
    min = "0.128.0"
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 10

  [[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 20

  [[menu.main]]
    name = "Submit Events"
    url = "/submit/"
    weight = 30