baseURL = "http://fallonevents.com/"
languageCode = "en-us"
title = "Fallon Events"
theme = "Agnes"

[params]
	dateFormat = "Jan 2, 2023" 
	authorName = "Fallon Events"
	google_analytics_id = "GA-"
	
[menu]
	[[menu.main]]
		Name = "Contact"
		URL = "#"
		weight = 1
	
	[[menu.main]]
		Name = "About us"
		URL = "#"
		weight = 2
	
	[[menu.main]]
		Name = "FAQ's"
		URL = "#"
		weight = 3
	
	[[menu.main]]
		Name = "Support"
		URL = "#"
		weight = 4
		
[params.social]
#	TwitterURL = "https://twitter.com/podbharati"
#	GoogleURL = "http://google.com"
#	FacebookURL = "https://facebook.com/podbharati"
		
[params.content]
	LeadTitle = "Fallon Events"
	LeadDescription = "Our goal is to consolidate all events in Fallon, Nevada into one calendar. "
	ButtonCaption = "Check out our google calendar"
	ButtonURL = "https://calendar.google.com/calendar/u/1?cid=N2MxYThhMGU0YmUwN2NkY2ZkNGIzMDY4Mjk4Y2RlNmYwMGEzMmU4MzZlZjIzZTM1Mjc3ZTg4YTM2NTJmY2RmMkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "Submit an Event to the Calendar"
	FeatureDescription = "Fill out this form to submit an event to the calendar"
	FeatureImage = "images/feature-2.png"	
	Button2URL = "https://forms.gle/xdwqaX5djvHEgi8GA"
#
#[[params.feature]]
#	FeatureTitle = "Feature 2"
##	FeatureImage = "images/feature-2.png"
#
#[[params.feature]]
#	FeatureTitle = "Feature 3"
#	FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
#	FeatureImage = "images/feature-3.png"
#	
##	FeatureTitle = "Feature 4"
	#FeatureDescription = "A pseudo-Latin text used in web design, layout, and printing in place of English to emphasise design elements."
	#FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

#[[params.pricing]]
#	PricingTitle = "Starter"
#	PricingRate = "27"	
#	ButtonCaption = "Get Early Access"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"	
#
#[[params.pricing]]
#	PricingTitle = "Professional"
#	PricingRate = "97"
#	ButtonCaption = "Get Earlier Access"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"		
#	
#[[params.pricing]]
#	PricingTitle = "Business"
#	PricingRate = "147"
#	ButtonCaption = "Get Earliest Access"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"
#	[[params.pricing.Features]]
#		Description = "Lorem ipsum is common text"	
#