name = "fallonevents"
compatibility_date = "2024-08-25"

[env.production]
HUGO_VERSION = "0.133.1"
NODE_VERSION = "18"

[[env.production.build]]
command = "npm run deploy"

[build]
command = "npm run deploy"